In [1]:
import pandas as pd
import sqlite3

In [2]:
# Create database
conn = sqlite3.connect("output/scraped_data.db")
cursor = conn.cursor()

# Create table
create_tab_statement = """
CREATE TABLE IF NOT EXISTS nharieng(
    "Tỉnh/Thành phố" TEXT,
    "Thành phố/Quận/Huyện/Thị xã" TEXT,
    "Xã/Phường/Thị trấn" TEXT,
    "Đường phố" TEXT,
    "Chi tiết" TEXT,
    "Nguồn thông tin" TEXT,
    "Tình trạng giao dịch" TEXT,
    "Thời điểm giao dịch/rao bán" DATE,
    "Thông tin liên hệ" TEXT,
    "Giá rao bán/giao dịch" INTEGER,
    "Giá ước tính" INTEGER,
    "Loại đơn giá (đ/m2 hoặc đ/m ngang)" TEXT,
    "Đơn giá đất" REAL,
    "Lợi thế kinh doanh" TEXT,
    "Số tầng công trình" REAL,
    "Tổng diện tích sàn" REAL,
    "Đơn giá xây dựng" REAL,
    "Năm xây dựng" INTEGER,
    "Chất lượng còn lại" REAL,
    "Diện tích đất (m2)" REAL,
    "Kích thước mặt tiền (m)" REAL,
    "Kích thước chiều dài (m)" REAL,
    "Số mặt tiền tiếp giáp" INTEGER,
    "Hình dạng" TEXT,
    "Độ rộng ngõ/ngách nhỏ nhất (m)" REAL,
    "Khoảng cách tới trục đường chính (m)" REAL,
    "Mục đích sử dụng đất" TEXT,
    "Yếu tố khác" TEXT,
    "Tọa độ (vĩ độ)" REAL,
    "Tọa độ (kinh độ)" REAL,
    "Hình ảnh của bài đăng" TEXT,
    Web TEXT
);"""

create_unique_index = """
CREATE UNIQUE INDEX IF NOT EXISTS unique_index
ON nharieng(
            "Tỉnh/Thành phố",  
            "Thành phố/Quận/Huyện/Thị xã",  
            "Xã/Phường/Thị trấn",  
            "Đường phố",  
            "Giá rao bán/giao dịch",  
            "Giá ước tính",  
            "Đơn giá đất",  
            "Lợi thế kinh doanh",  
            "Số tầng công trình",  
            "Tổng diện tích sàn",  
            "Đơn giá xây dựng",  
            "Chất lượng còn lại",  
            "Diện tích đất (m2)",  
            "Kích thước mặt tiền (m)",  
            "Kích thước chiều dài (m)",  
            "Số mặt tiền tiếp giáp",  
            "Hình dạng",  
            "Độ rộng ngõ/ngách nhỏ nhất (m)",  
            "Khoảng cách tới trục đường chính (m)",  
            "Mục đích sử dụng đất");
"""

cursor.execute(create_tab_statement)
cursor.execute(create_unique_index)
conn.commit()
conn.close()

In [3]:
import pandas as pd

onehousing = pd.read_excel('output/Onehousing/30.12.2025-06.01.2026.xlsx')
onehousing.columns

Index(['Tỉnh/Thành phố', 'Thành phố/Quận/Huyện/Thị xã', 'Xã/Phường/Thị trấn',
       'Đường phố', 'Nguồn thông tin', 'Tình trạng giao dịch',
       'Thời điểm giao dịch/rao bán', 'Thông tin liên hệ',
       'Giá rao bán/giao dịch', 'Giá ước tính',
       'Loại đơn giá (đ/m2 hoặc đ/m ngang)', 'Đơn giá đất',
       'Số tầng công trình', 'Chất lượng còn lại', 'Đơn giá xây dựng',
       'Diện tích đất (m2)', 'Tổng diện tích sàn', 'Kích thước mặt tiền (m)',
       'Kích thước chiều dài (m)', 'Số mặt tiền tiếp giáp', 'Hình dạng',
       'Độ rộng ngõ/ngách nhỏ nhất (m)',
       'Khoảng cách tới trục đường chính (m)', 'Mục đích sử dụng đất',
       'Hình ảnh của bài đăng', 'Yếu tố khác'],
      dtype='object')

In [4]:
bds_path = 'output/07.11.2025-08.01.2026.xlsx'
onehousing_path =  'output/Onehousing/30.12.2025-06.01.2026.xlsx'

with sqlite3.connect("output/scraped_data.db") as conn:
    bds_df = pd.read_excel(bds_path)
    bds_df['Web'] = 'Batdongsan'
    onehousing_df = pd.read_excel(onehousing_path)
    onehousing_df['Web'] = 'Onehousing'
    print(bds_df.columns)

    bds_df.to_sql('nharieng', conn, if_exists='append', index=False)
    onehousing_df.to_sql('nharieng', conn, if_exists='append', index=False)
    
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM nharieng;")
    n_rows = cursor.fetchone()[0]
    print(n_rows)
    # Drop duplicated values
    # inspect_dup = """SELECT *, COUNT(*) FROM nharieng
    #               GROUP BY  Tỉnh/Thành phố ,  Thành phố/Quận/Huyện/Thị xã ,  Xã/Phường/Thị trấn ,  Đường phố ,  Giá rao bán/giao dịch ,  Giá ước tính ,  Đơn giá đất ,  Lợi thế kinh doanh ,  Số tầng công trình ,  Tổng diện tích sàn ,  Đơn giá xây dựng ,  Chất lượng còn lại ,  Diện tích đất (m2) ,  Kích thước mặt tiền (m) ,  Kích thước chiều dài (m) ,  Số mặt tiền tiếp giáp ,  Hình dạng ,  Độ rộng ngõ/ngách nhỏ nhất (m) ,  Khoảng cách tới trục đường chính (m) ,  Mục đích sử dụng đất
    #               HAVING COUNT(*) > 1"""
    # delete_dup = """DELETE FROM nharieng
    #                 WHERE rowid NOT IN (
    #                 SELECT MIN(rowid)
    #                 FROM nharieng
    #                 GROUP BY "Tỉnh/Thành phố",  
    #                         "Thành phố/Quận/Huyện/Thị xã",  
    #                         "Xã/Phường/Thị trấn",  
    #                         "Đường phố",  
    #                         "Giá rao bán/giao dịch",  
    #                         "Giá ước tính",  
    #                         "Đơn giá đất",  
    #                         "Lợi thế kinh doanh",  
    #                         "Số tầng công trình",  
    #                         "Tổng diện tích sàn",  
    #                         "Đơn giá xây dựng",  
    #                         "Chất lượng còn lại",  
    #                         "Diện tích đất (m2)",  
    #                         "Kích thước mặt tiền (m)",  
    #                         "Kích thước chiều dài (m)",  
    #                         "Số mặt tiền tiếp giáp",  
    #                         "Hình dạng",  
    #                         "Độ rộng ngõ/ngách nhỏ nhất (m)",  
    #                         "Khoảng cách tới trục đường chính (m)",  
    #                         "Mục đích sử dụng đất")"""

Index(['Tỉnh/Thành phố', 'Thành phố/Quận/Huyện/Thị xã', 'Xã/Phường/Thị trấn',
       'Đường phố', 'Chi tiết', 'Nguồn thông tin', 'Tình trạng giao dịch',
       'Thời điểm giao dịch/rao bán', 'Thông tin liên hệ',
       'Giá rao bán/giao dịch', 'Giá ước tính',
       'Loại đơn giá (đ/m2 hoặc đ/m ngang)', 'Đơn giá đất',
       'Lợi thế kinh doanh', 'Số tầng công trình', 'Tổng diện tích sàn',
       'Đơn giá xây dựng', 'Năm xây dựng', 'Chất lượng còn lại',
       'Diện tích đất (m2)', 'Kích thước mặt tiền (m)',
       'Kích thước chiều dài (m)', 'Số mặt tiền tiếp giáp', 'Hình dạng',
       'Độ rộng ngõ/ngách nhỏ nhất (m)',
       'Khoảng cách tới trục đường chính (m)', 'Mục đích sử dụng đất',
       'Yếu tố khác', 'Tọa độ (vĩ độ)', 'Tọa độ (kinh độ)',
       'Hình ảnh của bài đăng', 'Web'],
      dtype='object')
8460

In [5]:
bds_df.shape[0] + onehousing_df.shape[0]

8460

In [ ]:
import sqlite3

new_bds=pd.read_excel(bds_path)

cols = list(new_bds.columns)
placeholders = ",".join(["?"] * len(cols))
quoted_cols = ",".join(f'"{c}"' for c in cols)

sql = f"""
INSERT OR IGNORE INTO nharieng ({quoted_cols})
VALUES ({placeholders})
"""

with sqlite3.connect("output/scraped_data.db") as conn:
    conn.executemany(sql, new_bds.itertuples(index=False, name=None))
    conn.commit()

    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM nharieng;")
    n_rows = cursor.fetchone()[0]

In [7]:
with sqlite3.connect("output/scraped_data.db") as conn:
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM nharieng;")
    n_rows = cursor.fetchone()[0]
    print(n_rows)

8485

In [9]:
import sqlite3

with sqlite3.connect('output/scraped_data.db') as conn:
    cursor = conn.cursor()
    cursor.execute("""
        SELECT *
        FROM nharieng
        ORDER BY rowid DESC
        LIMIT 25;
    """)
    rows = cursor.fetchall()

for row in rows:
    print(row)

('Thành phố Hà Nội', 'Quận Hà Đông', 'Phường Hà Cầu', 'Đường Hà Cầu', 'Mặt ngõ', 'https://batdongsan.com.vn/ban-nha-rieng-duong-ha-cau-phuong-ha-cau/ban-chinh-chu-mat-ngo-thong-o-to-do-cua-kinh-doanh-sam-uat-mat-tien-5-m-55-m2-11-ty-75-pr44750448', 'Đang rao bán', '29/12/2025', None, 11750000000, 11515000000, 'đ/m2', 202375641.01, 'Tốt', None, 55.0, 8221171.0, None, 0.85, 55.0, 5.0, 11.0, 1, 'Chữ nhật', 5.0, 30.0, 'Đất ở', '- SIÊU PHẨM TRUNG TÂM HÀ ĐÔNG CÁCH PHỐ 30M Ô TÔ ĐỖ CỬA\n- HÀ CẦU MẶT NGÕ THÔNG KINH DOANH NHÀ ĐẸP Ở NGAY\n\n- Địa chỉ: 45A Hà Cầu Võ Thị Sáu Hà Đông\n- Diện tích sổ: 52m² Diện tích sử dụng 55m²\n- Nhà 4 tầng Mặt tiền 5m\n- Ô tô đỗ cửa ngõ thông tứ phía kinh doanh tốt\n- Giá chào: 11.75 tỷ\n- Sổ đỏ chuẩn chính chủ\n\nĐẶC ĐIỂM NỔI BẬT\n- Vị trí quá đỉnh: chỉ 30m ra mặt phố Võ Thị Sáu, trung tâm phường Hà Cầu\n- Ô tô đỗ cửa, phù hợp mở spa văn phòng kinh doanh online tiệm tóc nail\n- Ngõ thông tứ tung giao thương cực mạnh\n- Nhà dân xây cực kiên cố chắc chắn khách xem là mê\n- Dân trí cao an ninh tuyệt vời\n\nTHIẾT KẾ CHUẨN CÔNG NĂNG\n- Nhà 4 tầng rộng mặt tiền 5m thoáng sáng\n- Tầng 1: Phòng khách Bếp WC\n- Tầng 2: 2 phòng ngủ 1 WC\n- Tầng 3: 1 phòng ngủ 1 phòng thờ 1 WC\n- Tầng 4: Sân phơi rộng, thoáng\n- Tổng 3 ngủ + 1 phòng đa năng\n\nTIỆN ÍCH XUNG QUANH BƯỚC CHÂN LÀ TỚI\n- 1 phút ra phố Võ Thị Sáu Quang Trung\n- 3 phút tới Chợ Hà Đông\n- 5 phút tới Trung tâm thương mại Mê Linh Plaza, Aeon Mall Hà Đông\n- Gần trường Lê Lợi, chuyên Nguyễn Huệ, bán công Trần Đăng Ninh\n- Gần bệnh viện 103, viện Bỏng, viện K Tân Triều\n- Bao quanh bởi: siêu thị, ngân hàng, nhà thuốc, sân chơi, bãi gửi ô tô\n\n10 TUYẾN ĐƯỜNG KẾT NỐI CỰC NHANH\n1 Võ Thị Sáu\n2 Quang Trung\n3 Nguyễn Trãi Trần Phú\n4 Tố Hữu Lê Văn Lương\n5 Lê Trọng Tấn\n6 Nguyễn Viết Xuân\n7 Trần Đăng Ninh\n8 Lê Lợi\n9 Đường 19/5\n10 KĐT Mỗ Lao Làng Việt Kiều Châu Âu\n\nPHÁP LÝ CAM KẾT\n- Sổ đỏ chính chủ không tranh chấp\n- Hoàn toàn không quy hoạch', 20.9685364001936, 105.772164277865, '["https://file4.batdongsan.com.vn/crop/600x315/2025/12/09/20251209092432-a7bc_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/09/20251209092452-a3e5_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/09/20251209092452-c94c_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/09/20251209092452-d5fa_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/09/20251209092452-b248_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/09/20251209092452-2288_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/09/20251209092452-9feb_wm.jpg"]', None)
('Thành phố Hồ Chí Minh', 'Thành phố Thủ Đức', 'Phường Tăng Nhơn Phú A', 'Đường Man Thiện', 'Mặt ngõ', 'https://batdongsan.com.vn/ban-nha-rieng-duong-man-thien-phuong-tang-nhon-phu-a/-moi-xay-chinh-chu-co1pn-tret-hop-gd-co-ong-ba-o-ke-ubnd-bv-quan-9-truong-hoc-pr44920902', 'Đang rao bán', '29/12/2025', None, 5950000000, 5831000000, 'đ/m2', 101821892.2, 'Khá', None, 90.0, 8221171.0, None, 1.0, 50.0, 4.23, 11.82, 1, 'Chữ nhật', 5.0, 0.0, 'Đất ở', 'Nhà 1 trệt 1 lửng, 1 sẹc đường Man Thiện, khu vip P. Tăng Nhơn Phú A, Q9.\nGiá 5.950 tỷ.\n- Diện tích 50m² (ngang 4.23m), sàn 90m².\n- Sân, PK, bếp, 1PN dưới đất, 2PN lửng, 2WC.\n- Hẻm ô tô 6m đường thông, cách Lê Văn Việt 300m tiện ích sát bên.\nAnh chị mua nhà ở và đầu tư cho thuê dưới 6 tỷ hãy gọi ngay nhà đất gia lạc\n0966 943 ***\nđể xem nhà và tư vấn hỗ trợ.', 10.8509734178928, 106.79523671871, '["https://file4.batdongsan.com.vn/crop/600x315/2025/12/29/20251229195616-ea0d_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/29/20251229195616-dc98_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/29/20251229195616-aff1_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/29/20251229195616-9a75_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/29/20251229195616-fd9b_wm.jpg"]', None)
('Thành phố Hồ Chí Minh', 'Quận Gò Vấp', 'Phường 6', 'Đường Lê Đức Thọ', 'Mặt ngõ', 'https://batdongsan.com.vn/ban-nha-rieng-duong-le-duc-tho-phuong-6-14/ban-1-5-tam-hxh-p6-sat-mat-tien-gia-9-25-ty-thuong-luong-pr44604777', 'Đang rao bán', '06/01/2026', None, 9000000000, 8820000000, 'đ/m2', 153832885.6, 'Tốt', None, 183.0, 8221171.0, None, 0.75, 50.0, 4.0, 12.5, 1, 'Chữ nhật', 5.0, 10.0, 'Đất ở', 'Bán nhà 1/ HXH Lê Đức Thọ P6 Gò Vấp (phường An Nhơn)\n- Diện tích: 4x12m sàn xây dựng 183m2\n- Kết cấu: trệt 1 lửng 3 lầu gồm 4PN, 4WC\n- Vị trí đẹp, gần chợ An Nhơn, trường học, đường lớn, đông đúc\n- Giá bán: 9 tỷ thương lượng', 10.8372639595925, 106.680696142583, '["https://file4.batdongsan.com.vn/crop/600x315/2025/11/21/20251121141021-055e_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/11/21/20251121141021-4357_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/11/21/20251121141021-5980_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/11/21/20251121141021-b113_wm.jpg"]', None)
('Thành phố Hồ Chí Minh', 'Quận 10', 'Phường 13', 'Đường Tô Hiến Thành', 'Mặt ngõ', 'https://batdongsan.com.vn/ban-nha-rieng-duong-to-hien-thanh-phuong-13-5/co-hoi-so-huu-hxh-q-10-dt-gan-90m-3-tang-dong-tien-on-dinh-gia-chi-12-3-ty-pr44346512', 'Đang rao bán', '03/01/2026', None, 11800000000, 11564000000, 'đ/m2', 115763174.85, 'Tốt', None, 223.3, 8221171.0, None, 0.75, 88.0, 4.4, 20.0, 1, 'Chữ nhật', 5.0, 10.0, 'Đất ở', 'Địa chỉ: Tô Hiến Thành, Phường 13, Quận 10.\n\nVị trí: Vô cùng đắc địa, nằm trong hẻm xe hơi rộng rãi, khu vực trung tâm Quận 10, gần các trục đường lớn. Vị trí an ninh, dân trí cao, rất thuận tiện để kinh doanh và đi lại.\n\nDiện tích: 3.6m x 25m, vuông vức. Diện tích công nhận: 88.5m².\n\nKết cấu: Nhà kiên cố với 3 Tầng (Tổng cộng 4 Tầng khai thác). Tổng diện tích sử dụng (DTSD): 223.3m².\n\nHợp đồng thuê (HĐT): Đang cho Spa thuê với giá 23 triệu/tháng, đảm bảo dòng tiền ổn định ngay khi mua.\n\nƯu điểm nổi bật:\nGiá đầu tư CỰC TỐT: Với mức giá 11,8 tỷ cho một tài sản có quy mô 4 tầng, dòng tiền 23 triệu/tháng và nằm trong hẻm xe hơi tại Quận 10, đây là cơ hội hiếm có để đầu tư sinh lời.\n\nKhuôn đất Dài, Tối ưu khai thác: Chiều dài 25m giúp tối ưu hóa không gian kinh doanh (Spa, văn phòng) và sinh hoạt.\n\nKết cấu cao tầng: Nhà 4 tầng với tổng DTSD hơn 223m², rất phù hợp để làm văn phòng công ty, thẩm mỹ viện hoặc tiếp tục cho thuê tạo dòng tiền.\n\nDòng tiền ổn định: Khai thác sẵn 23 triệu/tháng, đảm bảo khả năng hoàn vốn và tính thanh khoản.\n\nHẻm xe hơi, Dễ dàng giao thương: Hẻm rộng, xe hơi ra vào thoải mái.\n\nGiá bán: 11,8 Tỷ.\n\nĐây là cơ hội tuyệt vời để sở hữu một tài sản có dòng tiền mạnh, vị trí đắc địa, tiềm năng sinh lời cao với mức giá đã được điều chỉnh hợp lý. Anh nên nắm bắt ngay!', 10.7798703857952, 106.668047421571, '["https://file4.batdongsan.com.vn/crop/600x315/2025/10/22/20251022160206-2b2d_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/10/22/20251022160205-c9d3_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/10/22/20251022160206-11b0_wm.jpg"]', None)
('Thành phố Hồ Chí Minh', 'Thành phố Thủ Đức', 'Phường Linh Chiểu', 'Đường 16', 'Mặt ngõ', 'https://batdongsan.com.vn/ban-nha-rieng-duong-16-5-phuong-linh-chieu/cg-ban-can-ho-dich-vu-4-tang-hem-oto-ngay-dh-ngan-hang-hoang-dieu-2-21-phong-thu-nhap-1-ty-nam-pr44571778', 'Đang rao bán', '05/01/2026', None, 21300000000, 20874000000, 'đ/m2', 82749120.35, 'Trung bình', None, 500.0, 8221171.0, None, 0.75, 215.0, 5.2, 41.35, 1, 'Chữ nhật', 5.0, 10.0, 'Đất ở', 'BÁN CĂN HỘ DỊCH VỤ NGAY ĐH NGÂN HÀNG - HOÀNG DIỆU 2 - THU NHẬP 1 TỶ/ NĂM\n\n- Kết cầu: 1 trệt 3 lầu( 3 tầng + tum); đang có 21 phòng cho thuê.\n\n- Diện tích: 215m² ( 8m x 23m) - Diện tích sàn gần 500m², Hẻm Oto\n\n- Vị trí sát Trường Đại Học Ngân Hàng, Khu vực trung tâm, học sinh, sinh viên đông đức, thuê full quanh năm.\n\n- Giá: 21,3 tỷ - TLCC, Sổ riêng, hoàn công.', 10.8590605314264, 106.760749182229, '["https://file4.batdongsan.com.vn/crop/600x315/2025/11/17/20251117184000-3101_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/11/17/20251117183958-e7d6_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/11/17/20251117183959-065d_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/11/17/20251117183959-04dc_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/11/17/20251117184000-917c_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/11/17/20251117184001-403e_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/11/17/20251117184001-b64b_wm.jpg"]', None)
('Thành phố Hồ Chí Minh', 'Thành phố Thủ Đức', 'Phường Linh Đông', 'Đường Số 22', 'Mặt ngõ', 'https://batdongsan.com.vn/ban-nha-rieng-duong-so-22-phuong-linh-dong/ban-goc-2-mat-tien-22-thu-duc-gan-pham-van-gan-vanh-dai-2-xe-hoi-pr44955905', 'Đang rao bán', '05/01/2026', None, 7100000000, 6958000000, 'đ/m2', 73713283.83, 'Trung bình', None, 136.0, 8221171.0, None, 0.85, 81.5, 4.0, 20.38, 2, 'Chữ nhật', 5.0, 1000.0, 'Đất ở', 'BÁN NHÀ ĐƯỜNG 22 LINH ĐÔNG,THỦ ĐỨC\nCẦN BÁN NHANH CĂN GÓC 2 MẶT HẺM Ô TÔ TRÁNH NHAU\nGiá bán:7.1 tỷ còn thương lượng\nVị trí: Hẻm xe hơi đường 22, Phường Linh Đông, TP Thủ Đức\n*Diện tích đất: 81,5m² (ngang 6m dài 13,5m)\n- Diện tích sàn sử dụng: 136m2\n- Kết cấu: 1 trệt, 1 lầu, 1 tum (2 PN, 2 WC, 1 PK, 1 Bếp, Sân thượng trước, Sân thượng sau .Nhà xây kiên cố để ở, không phải xây để bán\n+ Nội thất đầy đủ\n- Sổ sạch hoàn công đầy đủ\n+ Xe hơi để trước nhà, hoặc để trong nhà đều được\n+ Gần trường học, bệnh viện, siêu thị, ủy ban và nằm trong KDC có dân trí cao, kế bên trung tâm thể thao\n+ Gần đường vành đai 2 (cách 800m), 1km ra Phạm Văn Đồng, 20 phút tới sân bay TSN\n+ Khu vực không bị ngập nước\n**Giá bán: 7,1 tỷ còn thương lượng', 10.8494151490057, 106.74360844448, '["https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105095554-63e1_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105095554-aeb8_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105095554-8b54_wm.jpg"]', None)
('Thành phố Hà Nội', 'Quận Hà Đông', 'Phường Kiến Hưng', 'Đường Đa Sỹ', 'Mặt ngõ', 'https://batdongsan.com.vn/ban-nha-rieng-duong-da-sy-phuong-kien-hung/ban-chinh-chu-ngo-thong-nong-thoang-vai-buoc-ra-o-to-full-cong-nang-35-m2-6-ty-7-pr44770680', 'Đang rao bán', '29/12/2025', None, 6700000000, 6566000000, 'đ/m2', 181210975.68, 'Trung bình', None, 32.0, 8221171.0, None, 0.85, 35.0, 4.0, 8.75, 1, 'Chữ nhật', 3.0, 10.0, 'Đất ở', 'SIÊU PHẨM ĐA SỸ NHÀ ĐẸP 5 TẦNG CÁCH Ô TÔ 30M\nGIÁ CHỈ 6.7 TỶ Ở NGAY FULL CÔNG NĂNG\n- Địa chỉ: Đa Sỹ Kiến Hưng Hà Đông\n- Diện tích sổ: 32m² Diện tích sử dụng: 35 m2\n- Nhà 5 tầng Mặt tiền 3.9m\n- Cách ô tô 30m Ngõ thoáng Giao thông thuận tiện\n- Giá chào: 6.7 tỷ (thương lượng trực tiếp chính chủ)\n- Sổ đỏ vuông A4 pháp lý chuẩn chỉnh\n\nĐẶC ĐIỂM NỔI BẬT TẦM GIÁ HIẾM CÓ NHÀ ĐẸP NHƯ NÀY\n- Nhà xây được vài năm còn rất mới, chỉ việc xách vali về ở\n- Vị trí đẹp: Đa Sỹ, vào 10m là tới\n- Ngõ trước nhà sạch sẽ thoáng dân trí cao\n- Cách ô tô đỗ chỉ 30m, thuận tiện di chuyển\n- Khu vực đông dân gần trường gần chợ tiện ích đủ đầy\n- Thửa đất vuông vắn như A4 hợp phong thủy dễ mua dễ bán\n\nTHIẾT KẾ HIỆN ĐẠI ĐẦY ĐỦ CÔNG NĂNG\n- Tầng 1: Phòng khách + Bếp + WC\n- Tầng 2 3 4: Mỗi tầng 1 phòng ngủ rộng + WC khép kín\n- Tầng 5: Phòng thờ, Sân phơi thoáng rộng đón nắng đẹp\n- Tổng 3 phòng ngủ lớn phù hợp gia đình trẻ / vợ chồng có con nhỏ\n\nTIỆN ÍCH XUNG QUANH BƯỚC RA LÀ ĐẦY ĐỦ\n- Gần chợ Đa Sỹ chợ Kiến Hưng\n- Gần trường cấp 1 2 3 Kiến Hưng\n- Vài phút ra: Tô Hiệu Quang Trung Nguyễn Viết Xuân Xa La\n- Dân cư thân thiện an ninh ổn định sạch sẽ\n\nPHÁP LÝ CAM KẾT\n- Sổ đỏ vuông vắn sang tên trong ngày\n- Nhà không tranh chấp không lỗi phong thủy', 20.9592595500529, 105.785296561017, '["https://file4.batdongsan.com.vn/crop/600x315/2025/12/11/20251211091549-d8f1_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/11/20251211091601-0c45_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/11/20251211091601-6404_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/11/20251211091601-515a_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/11/20251211091601-dfa7_wm.jpg"]', None)
('Thành phố Hồ Chí Minh', 'Quận 1', 'Phường Nguyễn Thái Bình', 'Đường Phó Đức Chính', 'Mặt ngõ', 'https://batdongsan.com.vn/ban-nha-rieng-pho-pho-duc-chinh-phuong-nguyen-thai-binh/can-ban-gap-hem-trung-tam-quan-1-pr44926997', 'Đang rao bán', '30/12/2025', None, 8200000000, 8036000000, 'đ/m2', 205923508.24, 'Tốt', None, 101.0, 8221171.0, None, 0.75, 36.0, 3.4, 10.59, 1, 'Chữ nhật', 3.0, 0.0, 'Đất ở', 'Hẻm 3M đường Phó Đức Chính, P. Nguyễn Thái Bình, Quận, diện tích 3.4 x 10.5 8.2 tỷ, Kết cấu gồm trệt, lửng, lầu và sân thượng, 3PN, 3WC,\n+ Vi trí siêu đẹp 5 phút ra chợ Bến Thành, 3 phút tối Bitexco, đầy đủ tiện ích xung quanh.\n+ Hẻm an ninh, sạch sẽ, sát mặt tiền, ô tô đỗ cách tầm 20m.\n+ Sổ đẹp vuôn vức, hoàn công đủ 101 m² sàn xây dựng, không quy hoạch không lộ giới.', 10.7688858941806, 106.699940481868, '["https://file4.batdongsan.com.vn/crop/600x315/2025/12/30/20251230151306-36e9_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/30/20251230151335-61d4_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/30/20251230151341-cf84_wm.jpg"]', None)
('Thành phố Hồ Chí Minh', 'Quận 8', 'Phường 7', 'Đường 19C', 'Mặt phố', 'https://batdongsan.com.vn/ban-nha-rieng-duong-19c-phuong-7-6/ban-can-khu-dan-cu-le-boi-ke-cong-vien-sieu-dep-pr44462201', 'Đang rao bán', '28/12/2025', None, 7000000000, 6860000000, 'đ/m2', 79584121.75, 'Tốt', None, 80.0, 8221171.0, None, 0.75, 80.0, 12.0, 6.67, 1, 'Chữ nhật', 12.0, 0.0, 'Đất ở', 'Bán nhà đường xe tải Khu Dân Cư Lê Bôi P7 quận 8. Nhà đối diện công viên, đất vuông vức (5m x 16m)\n\nDiện tích đất: 80m² (5m x 16m); Diện tích sàn: 215m2\n\nHiện trạng: 1 trệt 2 lầu sân thượng với 4 phòng ngủ, 3 toilet, hoàn công đủ\n\nHướng: Đông Bắc\n\nPháp lý: sổ hồng riêng (công chứng sang tên ngay)\n\n-- Giá bán- 7 tỷ thương lượng\n\nVị trí: mặt tiền đường 12m, nhà đối diện công viên', 10.7048794558008, 106.620887312564, '["https://file4.batdongsan.com.vn/crop/600x315/2025/11/05/20251105075417-5e3c_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/11/05/20251105075417-5ea5_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/11/05/20251105075418-cec1_wm.jpg"]', None)
('Thành phố Hồ Chí Minh', 'Quận Phú Nhuận', 'Phường 2', 'Đường Phan Xích Long', 'Mặt ngõ', 'https://batdongsan.com.vn/ban-nha-rieng-duong-phan-xich-long-phuong-2-21/ban-gap-trong-tuan-ban-32m-3-tang-6-85-ty-pr44892982', 'Đang rao bán', '25/12/2025', None, 6850000000, 6713000000, 'đ/m2', 191476298.95, 'Trung bình', None, 95.0, 8221171.0, None, 0.75, 32.0, 3.86, 8.29, 1, 'Chữ nhật', 3.0, 10.0, 'Đất ở', '- Vị trí trung tâm phố Phan Xích Long, Phú Nhuận, trong hẻm ba gác, cách mặt tiền chỉ 50m. Giao thông thuận lợi, gần các trục chính: Hoàng Văn Thụ, Trần Huy Liệu. Gần Đại học Văn Lang và Đại học Kiến Trúc TP.HCM.\n- Diện tích: 32m².\n- Kết cấu: 3 tầng (1 trệt, 2 lầu), tổng sàn 95m². Gồm 2 phòng ngủ, 3 wc.\n- Tiện ích: Đầy đủ nội thất. Hẻm thông thuận tiện.\n- Địa chỉ: Hẻm đường Phan Xích Long, Phường 2, Phú Nhuận.\n- Giá bán: 6.85 tỷ.', 10.7988430898593, 106.687991135434, '["https://file4.batdongsan.com.vn/crop/600x315/2025/12/25/20251225205232-187c_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/25/20251225205232-2122_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/12/25/20251225205232-a00c_wm.jpg"]', None)
('Thành phố Hồ Chí Minh', 'Huyện Nhà Bè', 'Xã Long Thới', 'Đường Nguyễn Văn Tạo', '126', 'https://batdongsan.com.vn/ban-nha-rieng-duong-nguyen-van-tao-xa-long-thoi/ban-nr-hem-126-be-dt-249m2-gia-ban-13-ty-944-trieu-56tr-m2-pr43174640', 'Đang rao bán', '07/01/2026', None, 13940000000, 13661200000, 'đ/m2', 51397498.17, 'Trung bình', None, 140.0, 8221171.0, None, 0.75, 249.0, 10.0, 24.9, 2, 'Chữ nhật', 8.0, 200.0, 'Đất ở', 'ĐC: 126/15/8/3 Nguyễn Văn Tạo - Ấp 3 xã Long Thới - huyện Nhà Bè - TP HCM.\n\n- [ ] Đường trước nhà rộng 10m.\n- [ ] Cách đường Nguyễn Văn Tạo khoảng 200m.\n- [ ] Ngay cạnh đường dẫn vào cao tốc Bến Lức - Long Thành.\n- [ ] Diện tích đất: 249m² (dài rộng - xem bản vẽ trong sổ hồng).\n- [ ] Diện tích nhà: 140m².\n- [ ] 3 phòng ngủ.\n- [ ] 2 WC.\n- [ ] 1 phòng khách.\n- [ ] Khu vực bếp và bàn ăn 3,6m x 6,8m.\n- [ ] Sân trước rộng khoảng 30m².\n- [ ] Sân sau rộng khoảng 35m².\n- [ ] Đường bên hông nhà nối sân trước và sân sau rộng khoảng 1,2m.\n- [ ] Nhà xây dạng Biệt Thự, mái ngói, tưởng 20, toàn bộ sàn nhà 140m² được đổ bê tông, móng băng kiên cố có thể lên thêm 1 tấm.\n- [ ] Sau nhà là rạch, tương lai gần sẽ làm cống hộp, nhà sẽ có 2 mặt tiền.\n- [ ] Sổ hồng - pháp lý rõ ràng.\n- [ ] Giá bán 13 tỷ 944 triệu (56 triệu / m²).\n- [ ] Xem nhà xin hẹn trước 1 ngày.', 10.6511156970164, 106.729976119815, '["https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112655-ff52_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112707-3512_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112704-e9ec_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112658-2d78_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112651-03d5_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112633-f107_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112631-62fa_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112635-00a2_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112637-b5aa_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112644-3309_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112645-0343_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112700-23ba_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2025/06/05/20250605112648-28e6_wm.jpg"]', None)
('Thành phố Hà Nội', 'Quận Hà Đông', 'Phường Văn Quán', 'Đường Lương Ngọc Quyến', 'Mặt ngõ', 'https://batdongsan.com.vn/ban-nha-rieng-duong-luong-ngoc-quyen-phuong-van-quan/ban-ngo-o-to-80m-su-dung-moi-6-ty-gan-pho-tran-phu-pr44898043', 'Đang rao bán', '26/12/2025', None, 6100000000, 5978000000, 'đ/m2', 58201051.22, 'Tốt', None, 90.0, 8221171.0, None, 1.0, 90.0, 5.29, 17.01, 1, 'Chữ nhật', 5.0, 70.0, 'Đất ở', 'Bán nhà ngõ ô tô Lương Ngọc Quyến Văn Quán 90m² sử dụng nhà mới 6.1 tỷ gần phố Trần Phú.\n\nThông tin chi tiết:\nĐịa chỉ: Lương Ngọc Quyến Văn Quán Hà Đông.\nDiện tích sổ đỏ: 48.8m². Diện tích sử dụng thực tế 90m².\nMặt ngõ rộng, ô tô đỗ cửa vị trí cực thuận tiện.\nNhà xây kiên cố, mới thiết kế:\n3 phòng ngủ.\nPhòng khách rộng bếp riêng biệt.\n2 vệ sinh lớn.\nSân để xe trước nhà sân phơi phía sau thoáng trước sau.\n\nTiện ích khu vực:\nCách phố Trần Phú 70m gần Royal City.\nGần trường học các cấp, Đại học lớn.\nChợ, siêu thị, quán ăn tiện ích không thiếu.\nPhù hợp để ở, kinh doanh nhỏ, cho thuê.\n\nPháp lý: Sổ đỏ chính chủ giao dịch nhanh gọn.\n\nGiá bán: 6.1 tỷ thương lượng.', 20.9841730101081, 105.794877397602, '["https://file4.batdongsan.com.vn/crop/600x315/2026/01/07/20260107121234-f57b_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2026/01/07/20260107121234-e845_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2026/01/07/20260107121235-fda6_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2026/01/07/20260107121236-b075_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2026/01/07/20260107121237-7504_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2026/01/07/20260107121238-beab_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2026/01/07/20260107121238-5c9d_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2026/01/07/20260107121240-d07f_wm.jpg", "https://file4.batdongsan.com.vn/crop/600x315/2026/01/07/20260107121241-d6e1_wm.jpg"]', None)

In [10]:
import sqlite3
import pandas as pd

db_path = "output/scraped_data.db"
out_path = "output/nharieng_export.xlsx"

with sqlite3.connect(db_path) as conn:
    df = pd.read_sql_query("SELECT * FROM nharieng", conn)

df.to_excel(out_path, index=False)

In [16]:
df[df['Nguồn thông tin'] == "https://batdongsan.com.vn/ban-nha-rieng-duong-nguyen-huu-canh-phuong-22/can-ban-hem-ba-gac-p22-tret-lau-duc-pr44918979"]

,Tỉnh/Thành phố,Thành phố/Quận/Huyện/Thị xã,Xã/Phường/Thị trấn,Đường phố,Chi tiết,Nguồn thông tin,Tình trạng giao dịch,Thời điểm giao dịch/rao bán,Thông tin liên hệ,Giá rao bán/giao dịch,...,Số mặt tiền tiếp giáp,Hình dạng,Độ rộng ngõ/ngách nhỏ nhất (m),Khoảng cách tới trục đường chính (m),Mục đích sử dụng đất,Yếu tố khác,Tọa độ (vĩ độ),Tọa độ (kinh độ),Hình ảnh của bài đăng,Web
52,Thành phố Hồ Chí Minh,Quận Bình Thạnh,Phường 22,Đường Nguyễn Hữu Cảnh,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,29/12/2025,None,6.800000e+09,...,1,Chữ nhật,3.0,10.0,Đất ở,Bình Thạnh\nCần bán nhà hẻm ba gác đường Nguyễ...,10.7935,106.718105,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
8460,Thành phố Hồ Chí Minh,Quận Bình Thạnh,Phường 22,Đường Nguyễn Hữu Cảnh,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,29/12/2025,None,6.800000e+09,...,1,Chữ nhật,3.0,10.0,Đất ở,Bình Thạnh\nCần bán nhà hẻm ba gác đường Nguyễ...,10.7935,106.718105,"[""https://file4.batdongsan.com.vn/crop/600x315...",None

In [17]:
df.iloc[52] == df.iloc[8460]

Tỉnh/Thành phố                           True
Thành phố/Quận/Huyện/Thị xã              True
Xã/Phường/Thị trấn                       True
Đường phố                                True
Chi tiết                                 True
Nguồn thông tin                          True
Tình trạng giao dịch                     True
Thời điểm giao dịch/rao bán              True
Thông tin liên hệ                       False
Giá rao bán/giao dịch                    True
Giá ước tính                             True
Loại đơn giá (đ/m2 hoặc đ/m ngang)       True
Đơn giá đất                              True
Lợi thế kinh doanh                       True
Số tầng công trình                      False
Tổng diện tích sàn                       True
Đơn giá xây dựng                         True
Năm xây dựng                            False
Chất lượng còn lại                       True
Diện tích đất (m2)                       True
Kích thước mặt tiền (m)                  True
Kích thước chiều dài (m)                 True
Số mặt tiền tiếp giáp                    True
Hình dạng                                True
Độ rộng ngõ/ngách nhỏ nhất (m)           True
Khoảng cách tới trục đường chính (m)     True
Mục đích sử dụng đất                     True
Yếu tố khác                              True
Tọa độ (vĩ độ)                           True
Tọa độ (kinh độ)                         True
Hình ảnh của bài đăng                    True
Web                                     False
dtype: bool

In [20]:
df.iloc[[52, 8460]][['Thông tin liên hệ', 'Số tầng công trình', 'Năm xây dựng', 'Web']]

     Thông tin liên hệ  Số tầng công trình Năm xây dựng         Web
52                None                 NaN         None  Batdongsan
8460              None                 NaN         None        None

In [21]:
df.iloc[52]['Số tầng công trình'] == df.iloc[8460]['Số tầng công trình']

np.False_

In [24]:
type(df.iloc[8460]['Số tầng công trình'])

numpy.float64